language: go

sudo: false

go: 1.6

cache:
  directories:
    - $HOME/.cache

go_import_path: github.com/skygeario/skycli

before_install:
  - >
    go get golang.org/x/tools/cmd/stringer \
           golang.org/x/tools/cmd/cover \
           github.com/golang/lint/golint \
           github.com/rickmak/gocyclo \
           github.com/oursky/gogocyclo \
           github.com/Masterminds/glide \
           github.com/mitchellh/gox

install:
  - glide install
  - go install

script:
  - golint commands | grep -v -f .golint.exclude; test $? -eq 1
  - golint container | grep -v -f .golint.exclude; test $? -eq 1
  - golint record | grep -v -f .golint.exclude; test $? -eq 1
  - go generate commands/... && go generate container/... && go generate record/...
  - gocyclo -over 15 commands | gogocyclo
  - gocyclo -over 15 container | gogocyclo
  - gocyclo -over 15 record | gogocyclo
  - go test -cover $(glide nv -x)

before_deploy:
  - make all

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - dist/*
    skip_cleanup: true
    file_glob: true
    on:
      repo: SkygearIO/skycli
      tags: true

notifications:
  slack: 
    secure: "bjiIoq/mo5VC+avVuqxoK9kAC/WwgChLz4gOXTW4mAVtOETEpjI18hVQDytVg2I/4Mv8cxjfsKLrEn0QcR6q8rbLy2XAR91iwWlNFhVfnK8velawzz2E8wCEhBgbLtcRg6pDf+LMDDJEa5ripbeoW0XEoGtpij7pHz+84g/VwWhF3j1kw5hgH0FT61MJQQRWOeVnFR2hFpKKekfTSyPhVuRGo8kza3xL9bTsprxf/EZI0bX9vTad6EtsIvO2o+w+wjkCuJZ0zIEnGXbud+Ll9aq9rYcbQHLzPrgxXVJjx26Reu66/Gu1gvFsNhiEtHxtdxWtgjT7tdXE9DzZP9p0CVsTLOiH6qstcJGRHECz5kV7XyvXl2Mc8VNkBqY4x1yJ8b41TU4ipz17IxCBV8B9KTLtyWAp0nVeRHKKPIemuXzGdeppvCZWZ9bgWskw7bF1qcMMomE9sLSvFYJC7MHQdvgVFzjOi9Yz9B5mecD2YaKesOFwO62k3JnG4roWr4FbilHcQI9Lfuwuu15IyRjRCN/6vdiHQh88k4KKKqM64Ytz4DXMz1tR+ij8FpS2MBKWaREVMnBF8EK0xe79Ie5L67i8MW/DBhNt5sKpFUQAfky6qUhM/uGhO/QN6tQrJLVKlWacO8Ie0psL6HH80398KEZ2/wnIpWp974W8fmzn2ts="

env:
  global:
    # GITHUB_RELEASE_TOKEN (cheungpat)
    - secure: "knbboDIpGnk+rbKs9Q6T1/Bai6NBfBo5dGy8UwIXXmQOgFpOL5OM4NEajckZl5dIrQiKlqR+3iuMRDLTlCeOtzCJ/r3QVlo62dWQsiBxb8GZHQNQXnBxqy9nlVeuuGA2qZwJStW0osnKcPyRTodlO4DR9MXtdBgYGqr/kvI4/Gvn9y3NZdVxBYfohlsB5v8oe8M/wZrTtl8zLiDxW2TfMl56FMNpEJ0ZAbSEYdRAJoPPevXjBkD5Ej9cdizlfsKPibqbfRvYN7lDlQz9TsX+GkNNw57krOmJXbzdnGU3lhEtfqmWaWknMqgQErMDH9f1ml1lT5FsFSEP0LJyrE/qhyVMLFUs5o+Qah3Y/rBjHZSVFuVflkGoWli9s5yxxZxCi/avtOxJ2q8I4LWJIB4FVhZx8FGtMBe/hbbvtrNtTvJ1Kt8BXG8zwLJFTk14+vvaBAyfK3mvMsHZaT/aGo/YQ7rgq1ISam4+yVuXjtVvj8rAEZQ8YX3/rBLUxSqzyTQt844Wk8B9pmqcJAP3ngUJaTCNn9ePPLWI0GbfeFzjMWPyft7MwcVq54hTVG6JpYQb8FXAAD+sUTJRvY5KzZpITqXFVm10CCl2quWs/3H9jBqHiUCi9zoxYtSiHOFu4YmLimqJhL8mxiuL1twWkT1aVBD2bPbcbIXw8GeQ+QcoQDk="
