language: go

sudo: false

go:
  - 1.5
  - 1.6

cache:
  directories:
    - $HOME/.cache
    - Godeps/_workspace

go_import_path: github.com/skygeario/skycli

before_install:
  - >
    go get golang.org/x/tools/cmd/stringer \
           golang.org/x/tools/cmd/cover \
           github.com/golang/lint/golint \
           github.com/smartystreets/goconvey/convey \
           github.com/smartystreets/assertions \
           github.com/rickmak/gocyclo \
           github.com/oursky/gogocyclo
  - go get github.com/inconshreveable/mousetrap # godep does not include this

script:
  - golint ./... | grep -v -f .golint.exclude; test $? -eq 1
  - go generate ./...
  - gocyclo -skip-godeps -over 15 . | gogocyclo
  - go test -cover ./...

before_deploy:
  - ./scripts/build-binary.sh

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - dist/*
    skip_cleanup: true
    file_glob: true
    on:
      repo: SkygearIO/skycli
      go: 1.5
      tags: true
  - provider: script
    script: ./scripts/upload-binary.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skycli
      all_branches: true
      go: 1.5

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh

env:
  global:
    # BINTRAY_API_KEY (skygeario-builder)
    - secure: "QNi+KqLGW9to8oY3AjPdl43FRgJpaCHZYM+ZXqDlUZFqwbD3TTPisFjA4EGNYtfKGOKyd4gyPuyaxNsmGrAkpTwNRyHYt7u0q09Hchi/pVDleVh8wpVV5StPUQI6Uxre3NPwbyYdfnzHCKKC8A0SDldjRvkeijmmFdWEVQI31BliinUbmUt7Z1fu0CCDBzoZ/Nz6clS9tLe8P8ZJEJIGqUOMGHvBy7QHRmccGEd6LTxYH75A3Fef0Fy4CwEC3+LMSwSxfOtbG2cj8lxOT2SXraFRfoAgRxUaVM/n04xippmDDrszrQDVKS6j0S0jyfc0D4o3HANo50gsDDArogBnTqI1nf/DgzT2VjKPJEUke3Ky8JV/JvQHQSo1iJq5nyN/L4I+/f4jbvjRHFJ/GSBes1RuCCGM/H62H9/Oa4NxVfWm4x5L9mebUvnueVILdgh1CH03SPao9KTm4qG9MI7mifX0gne7aep+sqNEUdiOgEkSp3Xd5cF7+T+k4ZTPkN5oNb4d34EoraeSWp5FaOuVcUKK3nRoSF2at0JnjTa9jWRqibRuQ/Oiz6uddKAqNc5KNf32aVTPl5iNTb08RJCxT9RgO4oNYzKWmy1lBldNajBzJiUFITY5ZoE1DVqNwYnM9IU7ufVUM/22d/IErAseiXR7ac6OOCZPZ9L2aWMY1gM="
    # GITHUB_RELEASE_TOKEN (cheungpat)
    - secure: "jXN08RO9pgV9UkQw05h3a76wo6cHLf+kdNW9yafUIIoagzCrWqn7fB2+ZLIC3ba/m7EOjVglLa9GaD6uK8ZFAimiT3AWpn/8/D+6hK/I8poGHZJOsFXfLLIPcQhn9BPehyPrldQb81+U0/c7Abgu12s2zDwZFjz1K6AcLJAcgj6ge0xvU5znfLDrdDTEy8rFh1X512frmF6AjB/Pq5BUhAjhiKjiPoIwjsiq232a6UFOaxcsw346TTL+6o7pW1v1/mEvOhilhbo2SbfkbcalntjZLoOBTsH1kWENZg4iLkiJ5ZKCrjgMWt10WAxkCopkAyvuF+/a+4YgKKnH8ghXPNKu5LQm2n7AGK5DYmPkbqO3qvqsqNqIC7RM2AwOEt3XOG2f2WQEirTHmLaaxSC8vLRed9loCVYlspH2i9tHXA2KAv9pQ7cPuuTkpp7OuE886g6ck7hMao8cnCCcdfRy1zpJDEJP9Q/D8IdnL0/WEMa6/rfXQJT8P2SFAYv5l663KkrpPykpLAFpZQIbgZa+yVgMPdBTWPC+O6cF84wiWLv/ruv0TOWf5lq0or/GtpIlHkUxvI3f9fCvnl6BCxdTJBwW+/Mj8x+oY8ZzsGW8vqxdDz5qfT9shwfqj6G35XvGcUqbOm9ySQwu5dWI/gCPlJ4Y0gFFBl4n2fuaKFJjXVo="
